import React from "react";
import Head from "next/head";

import {FileUploader} from "../components"
import styles from "../styles/Home.module.css";

export default function Home() {
  const [columns, setColumns] = React.useState<any[]>([]);
  const [rows, setRows] = React.useState<any[]>([]);

  const setCSVData = ({rows, columns}: { columns: string[]; rows: string[] | number[] }) => {
    setRows(rows);
    setColumns(columns)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FileUploader setCSVData={setCSVData} />
    </div>
  );
}
