import React from "react";
import Head from "next/head";

import { FileUploader, LineGraph } from "../components";
import { Render } from "../shared";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [columns, setColumns] = React.useState<string[]>([]);
  const [rows, setRows] = React.useState<Array<Array<any>>>([]);
  const [graphData, setGraphData] = React.useState<any[]>([]);

  const setCSVData = ({
    rows,
    columns,
  }: {
    columns: string[];
    rows: Array<Array<any>>;
  }) => {
    setRows(rows);
    setColumns(columns);
    const data = transformDataForGraph(rows);
    setGraphData(data);
  };

  const transformDataForGraph = (data: Array<Array<any>>) => {
    const transformedData = data.map(([name, value]) => ({
      name,
      value,
    }));
    return transformedData;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FileUploader setCSVData={setCSVData} />
      <Render
        condition={columns.length > 0}
        renderIf={() => <LineGraph data={graphData} />}
      />
    </div>
  );
}
